//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferMoney.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public decimal Balance { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
